insert into public.region (name) values
('Grad Beograd'),
('Južna i istočna Srbija'),
('Vojvodina'),
('Šumadija i zapadna Srbija'),
('Kosovo i Metohija');

insert into public.okrug (name, region_id) values
('Beogradski',1),
('Borski',2),
('Braničevski',2),
('Jablanički',2),
('Južnobački',3),
('Južnobanatski',3),
('Kolubarski',4),
('Kosovski',5),
('Kosovskomitrovački',5),
('Kosovskopomoravski',5),
('Mačvanski',4),
('Moravički',4),
('Nišavski',2),
('Pčinjski',2),
('Pećki',5),
('Pirotski',2),
('Podunavski',2),
('Pomoravski',4),
('Prizrenski',5),
('Rasinski',4),
('Raški',4),
('Severnobački',3),
('Severnobanatski',3),
('Srednjebanatski',3),
('Sremski',3),
('Šumadijski',4),
('Toplički',2),
('Zaječarski',2),
('Zapadnobački',3),
('Zlatiborski',4);

INSERT INTO public.opstina (name, okrug_id) values
('Barajevo',1),
('Čukarica',1),
('Grocka',1),
('Lazarevac',1),
('Mladenovac',1),
('Novi Beograd',1),
('Obrenovac',1),
('Palilula',1),
('Rakovica',1),
('Savski venac',1),
('Sopot',1),
('Stari grad',1),
('Surčin',1),
('Voždovac',1),
('Vračar',1),
('Zemun',1),
('Zvezdara',1),
('Bor',2),
('Kladovo',2),
('Majdanpek',2),
('Negotin',2),
('Golubac',3),
('Kučevo',3),
('Malo Crniće',3),
('Petrovac na Mlavi',3),
('Požarevac',3),
('Veliko Gradište',3),
('Žabari',3),
('Žagubica',3),
('Bojnik',4),
('Crna Trava',4),
('Lebane',4),
('Leskovac',4),
('Medveđa',4),
('Vlasotince',4),
('Bač',5),
('Bačka Palanka',5),
('Bački Petrovac',5),
('Bečej',5),
('Beočin',5),
('Novi Sad',5),
('Petrovaradin',5),
('Srbobran',5),
('Sremski Karlovci',5),
('Temerin',5),
('Titel',5),
('Vrbas',5),
('Žabalj',5),
('Alibunar',6),
('Bela Crkva',6),
('Kovačica',6),
('Kovin',6),
('Opovo',6),
('Pančevo',6),
('Plandište',6),
('Vršac',6),
('Lajkovac',7),
('Ljig',7),
('Mionica',7),
('Osečina',7),
('Ub',7),
('Valjevo',7),
('Glogovac',8),
('Kačanik',8),
('Kosovo Polje',8),
('Lipljan',8),
('Obilić',8),
('Podujevo',8),
('Priština',8),
('Štimlje',8),
('Štrpce',8),
('Uroševac',8),
('Kosovska Mitrovica',9),
('Leposavić',9),
('Srbica',9),
('Vučitrn',9),
('Zubin Potok',9),
('Zvečan',9),
('Gnjilane',10),
('Kosovska Kamenica',10),
('Novo Brdo',10),
('Vitina',10),
('Bogatić',11),
('Koceljeva',11),
('Krupanj',11),
('Loznica',11),
('Ljubovija',11),
('Mali Zvornik',11),
('Šabac',11),
('Vladimirci',11),
('Čačak',12),
('Gornji Milanovac',12),
('Ivanjica',12),
('Lučani',12),
('Aleksinac',13),
('Crveni Krst',13),
('Doljevac',13),
('Gadžin Han',13),
('Medijana',13),
('Merošina',13),
('Niš',13),
('Niška Banja',13),
('Pantelej',13),
('Ražanj',13),
('Svrljig',13),
('Bosilegrad',14),
('Bujanovac',14),
('Preševo',14),
('Surdulica',14),
('Trgovište',14),
('Vladičin Han',14),
('Vranje',14),
('Dečani',15),
('Đakovica',15),
('Istok',15),
('Klina',15),
('Peć',15),
('Babušnica',16),
('Bela Palanka',16),
('Dimitrovgrad',16),
('Pirot',16),
('Smederevo',17),
('Smederevska Palanka',17),
('Velika Plana',17),
('Ćuprija',18),
('Despotovac',18),
('Jagodina',18),
('Paraćin',18),
('Rekovac',18),
('Svilajnac',18),
('Gora',19),
('Orahovac',19),
('Prizren',19),
('Suva Reka',19),
('Aleksandrovac',20),
('Brus',20),
('Ćićevac',20),
('Kruševac',20),
('Trstenik',20),
('Varvarin',20),
('Kraljevo',21),
('Novi Pazar',21),
('Raška',21),
('Tutin',21),
('Vrnjačka Banja',21),
('Bačka Topola',22),
('Mali Iđoš',22),
('Subotica',22),
('Ada',23),
('Čoka',23),
('Kanjiža',23),
('Kikinda',23),
('Novi Kneževac',23),
('Senta',23),
('Nova Crnja',24),
('Novi Bečej',24),
('Sečanj',24),
('Zrenjanin',24),
('Žitište',24),
('Inđija',25),
('Irig',25),
('Pećinci',25),
('Ruma',25),
('Sremska Mitrovica',25),
('Stara Pazova',25),
('Šid',25),
('Aranđelovac',26),
('Batočina',26),
('Knić',26),
('Kragujevac',26),
('Lapovo',26),
('Rača',26),
('Topola',26),
('Blace',27),
('Kuršumlija',27),
('Prokuplje',27),
('Žitorađa',27),
('Boljevac',28),
('Knjaževac',28),
('Sokobanja',28),
('Zaječar',28),
('Apatin',29),
('Kula',29),
('Odžaci',29),
('Sombor',29),
('Arilje',30),
('Bajina Bašta',30),
('Čajetina',30),
('Kosjerić',30),
('Nova Varoš',30),
('Požega',30),
('Priboj',30),
('Prijepolje',30),
('Sjenica',30),
('Užice',30);

INSERT INTO public.groblje (name, opstina_id) values
('1300 kaplara',167),
('Aleja narodnih heroja',12),
('Aleja velikana',12),
('Aleja zaslužnih građana',12),
('Austrougarsko vojno groblje',12),
('Brankova glavica',145),
('Crkva Sv. Arhanđela',62),
('Hram Sv. Oca Nikolaja',62),
('Italijansko vojno groblje',12),
('Jevrejsko aškenasko',12),
('Jevrejsko groblje',16),
('Jevrejsko sefardsko',12),
('Kalemegdan',12),
('Novo groblje',139),
('Oslobodilaca Beograda',12),
('Stanovljansko groblje',170),
('Staro bežanijsko',6),
('Staro groblje',139),
('Staro katoličko',41),
('Zemunsko groblje',16),
('Manastir Svetog arhiđakona Stefana',185),
('Crvenoarmejsko',185),
('Partizansko',185),
('Britansko vojno groblje',12);