insert into public.region (name) values
('Grad Beograd'),
('Južna i istočna Srbija'),
('Vojvodina'),
('Šumadija i zapadna Srbija'),
('Kosovo i Metohija');

insert into public.okrug (name, region_id) values
('Beogradski',1),
('Borski',2),
('Braničevski',2),
('Jablanički',2),
('Južnobački',3),
('Južnobanatski',3),
('Kolubarski',4),
('Kosovski',5),
('Kosovskomitrovački',5),
('Kosovskopomoravski',5),
('Mačvanski',4),
('Moravički',4),
('Nišavski',2),
('Pčinjski',2),
('Pećki',5),
('Pirotski',2),
('Podunavski',2),
('Pomoravski',4),
('Prizrenski',5),
('Rasinski',4),
('Raški',4),
('Severnobački',3),
('Severnobanatski',3),
('Srednjebanatski',3),
('Sremski',3),
('Šumadijski',4),
('Toplički',2),
('Zaječarski',2),
('Zapadnobački',3),
('Zlatiborski',4);