import Head from 'next/head'
import { useState } from 'react'
import SearchBar from '../components/SearchBar'
import Link from 'next/link'

export default function Home() {
  const [results, setResults] = useState(null)
  return (
    <div>
      <Head>
        <title>Vecnost - Baza</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className='flex justify-center mt-5'>
          <SearchBar setResults={setResults} />
        </div>
          <div className='flex justify-center mt-5'>
          {results !== null && results.length === 0 && <div>Nema rezultata za ovu pretragu</div>}
          {results !== null && results.length > 0 && <div className='grid grid-cols-4 gap-8'>{results.map(result => 
            <Link passHref key={result.id} href={{pathname: '/entries/[id]', query:{id: result.id}}}>
            <ul className='mb-5 border border-gray-300 p-2 shadow-md hover:cursor-pointer hover:shadow-xl'>
              <li>Ime: {result.ime} {result.prezime}</li>
              <li>Rodjenje: {result.rodjenje}</li>
              <li>Smrt: {result.smrt}</li>
              <li>Groblje: {result.groblje}</li>
            </ul>
            </Link>)}</div>}
          </div>
      </main>
    </div>
  )
}
