-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE TABLE IF NOT EXISTS public.groblje
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name text COLLATE pg_catalog."default",
    opstina_id bigint,
    CONSTRAINT groblje_pkey PRIMARY KEY (id),
    CONSTRAINT groblje_id_key UNIQUE (id),
    CONSTRAINT groblje_opstina_id_fkey FOREIGN KEY (opstina_id)
        REFERENCES public.opstina (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.groblje
    OWNER to postgres;

GRANT ALL ON TABLE public.groblje TO anon;

GRANT ALL ON TABLE public.groblje TO authenticated;

GRANT ALL ON TABLE public.groblje TO postgres;

GRANT ALL ON TABLE public.groblje TO service_role;

COMMENT ON TABLE public.groblje
    IS 'Groblja';
