-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE TABLE IF NOT EXISTS public.okrug
(
    id smallint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 32767 CACHE 1 ),
    name character varying COLLATE pg_catalog."default",
    region_id smallint NOT NULL,
    CONSTRAINT okrug_pkey PRIMARY KEY (id),
    CONSTRAINT okrug_id_key UNIQUE (id),
    CONSTRAINT okrug_region_id_fkey FOREIGN KEY (region_id)
        REFERENCES public.region (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.okrug
    OWNER to postgres;

ALTER TABLE IF EXISTS public.okrug
    ENABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE public.okrug TO anon;

GRANT ALL ON TABLE public.okrug TO authenticated;

GRANT ALL ON TABLE public.okrug TO postgres;

GRANT ALL ON TABLE public.okrug TO service_role;

COMMENT ON TABLE public.okrug
    IS 'Okruzi';

CREATE POLICY "Enable access to all users"
    ON public.okrug
    AS PERMISSIVE
    FOR SELECT
    TO public
    USING (true);
