-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE TABLE IF NOT EXISTS public.region
(
    id smallint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 32767 CACHE 1 ),
    name character varying COLLATE pg_catalog."default",
    CONSTRAINT region_pkey PRIMARY KEY (id),
    CONSTRAINT region_id_key UNIQUE (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.region
    OWNER to postgres;

ALTER TABLE IF EXISTS public.region
    ENABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE public.region TO anon;

GRANT ALL ON TABLE public.region TO authenticated;

GRANT ALL ON TABLE public.region TO postgres;

GRANT ALL ON TABLE public.region TO service_role;

COMMENT ON TABLE public.region
    IS 'Regioni ';

CREATE POLICY "Enable access to all users"
    ON public.region
    AS PERMISSIVE
    FOR SELECT
    TO public
    USING (true);

